sudo: required
dist: trusty

language: java

before_install:
      - git clone https://github.com/snowch/biginsight-examples .
      - wget https://github.com/snowch/biginsight-examples/archive/master.zip
      - unzip master.zip
      - mv biginsight-examples-master/* .
      - openssl aes-256-cbc -K $encrypted_99124ea5561e_key -iv $encrypted_99124ea5561e_iv -in secrets.tar.enc -out secrets.tar -d
      - tar xvf secrets.tar
      - sudo sh -c 'echo "deb https://cran.r-project.org/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
      - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
      - gpg -a --export E084DAB9 | sudo apt-key add -
      - sudo apt-get -qq update
      - sudo apt-get -qq -y install r-base
      - sudo R CMD javareconf

env:
    - TESTS_TO_SKIP=BigSQLGroovy::Federation,BigR::LinearRegression
